# Generated by Django 4.0.2 on 2022-03-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimestampRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system_code', models.PositiveSmallIntegerField()),
                ('file_id', models.BigIntegerField()),
                ('pdf_file', models.FileField(blank=True, upload_to='')),
                ('status_cd', models.PositiveSmallIntegerField()),
            ],
            options={
                'abstract': False,
                'default_permissions': (),
            },
        ),
    ]
